### ISSUE TITLE
CS events calendar

### ISSUE THREAD

**Issue by junewunder** [jaywunder/crew-tv-dash#4]

**Comment by Dillonb** [comment]
Here is some HTML to embed the CS Crew calendar in agenda mode with most of the extra UI crap removed:

`<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=uvm.cscrew%40gmail.com&amp;color=%2323164E&amp;ctz=America%2FNew_York" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>`

**Comment by junewunder** [comment]
Thanks!
